spring:
  # 数据源配置项
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: kugga
        login-password: kuggaadmin!@#
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 1 # 初始连接数
        min-idle: 1 # 最小连接池数量
        max-active: 10 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        keep-alive: true
      primary: master
      datasource:
        master:
          name: kugga_db
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.master.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: kuggaadm
          password: '*****'
  #################### 定时任务相关配置 ####################
  # Quartz 配置项，对应 QuartzProperties 配置类
  quartz:
    auto-startup: true # 本地开发环境，尽量不要开启 Job
    scheduler-name: schedulerName # Scheduler 名字。默认为 schedulerName
    job-store-type: jdbc # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    properties: # 添加 Quartz Scheduler 附加属性，更多可以看 http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html 文档
      org:
        quartz:
          # Scheduler 相关配置
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO # 自动生成 instance ID
          # JobStore 相关配置
          jobStore:
            # JobStore 实现类。可见博客：https://blog.csdn.net/weixin_42458219/article/details/122247162
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true # 是集群模式
            clusterCheckinInterval: 15000 # 集群检查频率，单位：毫秒。默认为 15000，即 15 秒
            misfireThreshold: 60000 # misfire 阀值，单位：毫秒。
          # 线程池相关配置
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
    jdbc: # 使用 JDBC 的 JobStore 的时候，JDBC 的配置
      initialize-schema: NEVER # 是否自动使用 SQL 初始化 Quartz 表结构。这里设置成 never ，我们手动创建表结构。
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: '******'

#################### 相关配置 ####################

# 配置项，设置当前项目所有自定义的配置
kugga:
  pay:
    # 钱包
    wallet:
      appid: 5000000001
      app-secret: '******'
      should-sign: true
      sign-type: HMACSHA256
      platform-account: 41559830924304044032
      urls:
        APP_DETAIL: http://wallet.masquebar.xyz/app/detail
        CREATE_ACCOUNT: http://wallet.masquebar.xyz/account/create
        ACCOUNT_DETAIL: http://wallet.masquebar.xyz/account/detail
        PAYMENT_PREPAY: http://wallet.masquebar.xyz/payment/prepay
        PAYMENT_PAY_BY_BALANCE: http://wallet.masquebar.xyz/payment/payByBalance
        PAYMENT_DETAIL: http://wallet.masquebar.xyz/payment/detail
        PAYMENT_CANCEL: http://wallet.masquebar.xyz/payment/cancel
        ALLOCATION_APPLY: http://wallet.masquebar.xyz/allocation/apply
        ALLOCATION_RESULT: http://wallet.masquebar.xyz/allocation/result
        CHARGE_PRECHARGE: http://wallet.masquebar.xyz/charge/preCharge
        CHARGE_DETAIL: http://wallet.masquebar.xyz/charge/detail
        CHARGE_CANCEL: http://wallet.masquebar.xyz/charge/cancel
        DRAWBACK_APPLY: http://wallet.masquebar.xyz/drawback/apply
        DRAWBACK_DETAIL: http://wallet.masquebar.xyz/drawback/detail
        WITHDRAW_TO_PAYPAL: http://wallet.masquebar.xyz/withdraw/toPaypal
        WITHDRAW_DETAIL: http://wallet.masquebar.xyz/withdraw/detail
        REDPACKET_HANDOUT: http://wallet.masquebar.xyz/redPacket/handOut
        REDPACKET_DETAIL: http://wallet.masquebar.xyz/redPacket/detail
        PROOFREADBILL_APPLY: http://wallet.masquebar.xyz/proofreadBill/apply
        PROOFREADBILL_RESULT: http://wallet.masquebar.xyz/proofreadBill/result
  access-log: # 访问日志的配置项
    enable: true
  error-code: # 错误码相关配置项
    enable: false
  demo: false # 关闭演示模式

duke:
  league:
    # 后台的地址
    backed:
      subscribeOrderPay: http://172.18.0.121:80/app-api/league/subscribe/subscribeOrderPay
      subscribeEmailNotice: http://172.18.0.121:80/app-api/system/email/innerGeneralSend
      sendMessageClient: http://172.18.0.121:18081/app-api/system/messages/sendMessageClient
    # 跳转前端的地址
    fronted:
      subscribeView: https://www.kuggaduke.com/mine/subscribeView
